# Redirect /compilation to root landing page temporarily
[[redirects]]
  from = "/compilation"
  to = "/"
  status = 301

# Dirt redirects
[[redirects]]
  from = "/compilation/dirt"
  to = "https://dirt-fought.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/compilation/dirt/*"
  to = "https://dirt-fought.netlify.app/:splat"
  status = 200
  force = true

# Tooth redirects
[[redirects]]
  from = "/compilation/tooth"
  to = "https://tooth-lost.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/compilation/tooth/*"
  to = "https://tooth-lost.netlify.app/:splat"
  status = 200
  force = true

# Towels redirects
[[redirects]]
  from = "/compilation/towels"
  to = "https://towels.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from
